RBE 2000 level template code: ClearFaults Class Reference
ClearFaults Class Reference
#include <ClearFaults.h>
Public Member Functions
ClearFaults (StudentsRobot *robot)
virtual ~ClearFaults ()
void event (float *buffer)
Private Attributes
StudentsRobot * robotPointer
Detailed Description
Definition at line 6 of file ClearFaults.h.
Constructor & Destructor Documentation
ClearFaults()
ClearFaults::ClearFaults (StudentsRobot * robot) inline
Definition at line 10 of file ClearFaults.h.
~ClearFaults()
virtual ClearFaults::~ClearFaults () inline virtual
Definition at line 15 of file ClearFaults.h.
References event().
Member Function Documentation
event()
void ClearFaults::event (float * buffer)
Definition at line 6 of file ClearFaults.cpp.
References StudentsRobot::ClearFaults(), and robotPointer.
Referenced by ~ClearFaults().
Field Documentation
robotPointer
StudentsRobot* ClearFaults::robotPointer private
Definition at line 7 of file ClearFaults.h.
Referenced by event().
The documentation for this class was generated from the following files:
src/commands/ClearFaults.h
src/commands/ClearFaults.cpp