RBE 2000 level template code: HBridgeEncoderPIDMotor Class Reference
HBridgeEncoderPIDMotor Class Reference
#include <HBridgeEncoderPIDMotor.h>
Public Member Functions
HBridgeEncoderPIDMotor ()
virtual ~HBridgeEncoderPIDMotor ()
void attach (int pwmPin, int directionPin, int encoderA, int encoderB)
int64_t getPosition ()
int64_t getOutputMin ()
int64_t getOutputMax ()
int64_t getOutputMinDeadbad ()
int64_t getOutputMaxDeadbad ()
int64_t getOutputStop ()
void setOutput (int64_t out)
void overrideCurrentPositionHardware (int64_t val)
double calcCur (void)
double ticksToDeg ()
double getFreeSpinMaxDegreesPerSecond ()
Public Member Functions inherited from PIDMotor
PIDMotor ()
virtual ~PIDMotor ()
void loop ()
void velocityLoop ()
void overrideCurrentPosition (int64_t val)
void setSetpoint (int64_t val)
void startInterpolation (float newSetpoint, long msTimeDuration, interpolateMode mode)
void setSetpointDegrees (float val)
void startInterpolationDegrees (float newSetpoint, long msTimeDuration, interpolateMode mode)
void SetTunings (double Kp, double Ki, double Kd)
void SetTuningsVelocity (double Kp, double Kd)
void setVelocityDegreesPerSecond (float degreesPerSecond)
void pidinit ()
float getSetPointDegrees ()
double getVelocityDegreesPerSecond ()
double getAngleDegrees ()
void setOutputUnitVector (float out)
void stop ()
Data Fields
ESP32Encoder encoder
ESP32PWM motor
Data Fields inherited from PIDMotor
float unitDuration =1
RBEPID myPID
RBEPID velocityPID
int64_t hardwareOutput = 0
Private Attributes
int directionPin
Additional Inherited Members
Protected Member Functions inherited from PIDMotor
double calcVel ()
float myFmap (float x, float in_min, float in_max, float out_min, float out_max)
float getSetPoint ()
Protected Attributes inherited from PIDMotor
long lastTimeRunPID = 0
double Setpoint = 0
double Input = 0
double Output = 0
bool lastErrPositive = false
double curTime = 0
double prevTime = 0
double timeInterval = 0
double movement = 0
double prevPos = 0
double Vel = 0
float startSetpoint = 0
float endSetpoint = 0
float startTime = 0
float duration = 0
interpolateMode mode = LIN
float targetDegreesPerSecond = 0
Detailed Description
Definition at line 15 of file HBridgeEncoderPIDMotor.h.
Constructor & Destructor Documentation
HBridgeEncoderPIDMotor::HBridgeEncoderPIDMotor ()
Definition at line 10 of file HBridgeEncoderPIDMotor.cpp.
References directionPin.
HBridgeEncoderPIDMotor::~HBridgeEncoderPIDMotor () virtual
Definition at line 15 of file HBridgeEncoderPIDMotor.cpp.
Member Function Documentation
void HBridgeEncoderPIDMotor::attach (int pwmPin, int directionPin, int encoderA, int encoderB)
Attach the hardware
Parameters
pwmPin the pin number of the 10 khz PWM
directionPin the pin number of the pin used for direction of the H-Bridge
encoderA the A channel of the encoder
encoderB the B channel of the encoder
Definition at line 19 of file HBridgeEncoderPIDMotor.cpp.
References directionPin, encoder, motor, PIDMotor::pidinit(), and setOutput().
Referenced by StudentsRobot::attach().
double HBridgeEncoderPIDMotor::calcCur (void) virtual
calcCur
Returns
calcCur
Implements PIDMotor.
Definition at line 63 of file HBridgeEncoderPIDMotor.cpp.
double HBridgeEncoderPIDMotor::getFreeSpinMaxDegreesPerSecond () virtual
getFreeSpinMaxDegreesPerSecond
Returns
FreeSpinMaxDegreesPerSecond
Implements PIDMotor.
Definition at line 78 of file HBridgeEncoderPIDMotor.cpp.
int64_t HBridgeEncoderPIDMotor::getOutputMax () virtual
getOutputMax
Returns
OutputMax
Implements PIDMotor.
Definition at line 34 of file HBridgeEncoderPIDMotor.cpp.
References HBRIDGE_MAX.
int64_t HBridgeEncoderPIDMotor::getOutputMaxDeadbad () virtual
getOutputMaxDeadbad
Returns
OutputMaxDeadbad
Implements PIDMotor.
Definition at line 40 of file HBridgeEncoderPIDMotor.cpp.
References HBRIDGE_DEADBAND.
int64_t HBridgeEncoderPIDMotor::getOutputMin () virtual
getOutputMin
Returns
OutputMin
Implements PIDMotor.
Definition at line 31 of file HBridgeEncoderPIDMotor.cpp.
References HBRIDGE_MAX.
int64_t HBridgeEncoderPIDMotor::getOutputMinDeadbad () virtual
getOutputMinDeadbad
Returns
OutputMinDeadbad
Implements PIDMotor.
Definition at line 37 of file HBridgeEncoderPIDMotor.cpp.
References HBRIDGE_DEADBAND.
int64_t HBridgeEncoderPIDMotor::getOutputStop () virtual
getOutputStop
Returns
OutputStop
Implements PIDMotor.
Definition at line 43 of file HBridgeEncoderPIDMotor.cpp.
int64_t HBridgeEncoderPIDMotor::getPosition () virtual
getPosition
Returns
Position
Implements PIDMotor.
Definition at line 28 of file HBridgeEncoderPIDMotor.cpp.
References encoder.
Referenced by StudentsRobot::attach().
void HBridgeEncoderPIDMotor::overrideCurrentPositionHardware (int64_t val) virtual
overrideCurrentPositionHardware
forces the hardware provider to return this value instead of its internal value and this position
Parameters
val the value to set the sensor to
Implements PIDMotor.
Definition at line 58 of file HBridgeEncoderPIDMotor.cpp.
References encoder.
void HBridgeEncoderPIDMotor::setOutput (int64_t out) virtual
virtual setOutput Set the motor in raw motor units
this value should be pre scalled to match the motors range the zero deadbanding should already be taken care of
Implements PIDMotor.
Definition at line 46 of file HBridgeEncoderPIDMotor.cpp.
References directionPin, HBRIDGE_DEADBAND, and motor.
Referenced by attach().
double HBridgeEncoderPIDMotor::ticksToDeg () virtual
ticksToDeg
Returns
ticksToDeg
Implements PIDMotor.
Definition at line 70 of file HBridgeEncoderPIDMotor.cpp.
References encoder.
Field Documentation
int HBridgeEncoderPIDMotor::directionPin private
Definition at line 18 of file HBridgeEncoderPIDMotor.h.
Referenced by attach(), HBridgeEncoderPIDMotor(), and setOutput().
ESP32Encoder HBridgeEncoderPIDMotor::encoder
Definition at line 39 of file HBridgeEncoderPIDMotor.h.
Referenced by attach(), getPosition(), overrideCurrentPositionHardware(), and ticksToDeg().
ESP32PWM HBridgeEncoderPIDMotor::motor
Definition at line 40 of file HBridgeEncoderPIDMotor.h.
Referenced by attach(), and setOutput().
The documentation for this class was generated from the following files:
src/pid/HBridgeEncoderPIDMotor.h
src/pid/HBridgeEncoderPIDMotor.cpp