RBE 2000 level template code: ServoAnalogPIDMotor Class Reference
ServoAnalogPIDMotor Class Reference
#include <ServoAnalogPIDMotor.h>
Public Member Functions
ServoAnalogPIDMotor ()
void attach (int servoPin, int analogPin)
int64_t getPosition ()
void setOutput (int32_t out)
void overrideCurrentPositionHardware (int64_t val)
double calcCur (void)
Public Member Functions inherited from PIDMotor
int32_t getHardwareOutput ()
PIDMotor ()
virtual ~PIDMotor ()
void loop ()
void velocityLoop ()
void overrideCurrentPosition (int32_t val)
void setSetpoint (int32_t val)
void startInterpolation (float newSetpoint, long msTimeDuration, interpolateMode mode)
bool isInterpolationDone ()
float getInterpolationUnitIncrement ()
void setSetpointDegrees (float val)
void startInterpolationDegrees (float newSetpoint, long msTimeDuration, interpolateMode mode)
void SetTunings (double Kp, double Ki, double Kd)
void SetTuningsVelocity (double Kp, double Kd)
void setVelocityDegreesPerSecond (float degreesPerSecond)
void pidinit ()
float getSetPointDegrees ()
double getVelocityDegreesPerSecond ()
double getAngleDegrees ()
void setOutputUnitVector (float out)
void stop ()
int32_t getOutputMin ()
int32_t getOutputMax ()
int32_t getOutputMinDeadbad ()
int32_t getOutputMaxDeadbad ()
int32_t getOutputStop ()
double getFreeSpinMaxDegreesPerSecond ()
double ticksToDeg ()
void setOutputBoundingValues (int32_t outputMin, int32_t outputMax, int32_t outputStop, int32_t outputMinDeadbad, int32_t outputMaxDeadbad, double ticksToDeg, double getFreeSpinMaxDegreesPerSecond, double speedAtPositiveCreepValue)
Private Attributes
Servo motor
int adcPin =0
int64_t offset =0
float filterBuffer [filterSize]
int filterIndex =0
float filterSum =0
Additional Inherited Members
Data Fields inherited from PIDMotor
int32_t hardwareOutput = 0
float targetDegreesPerSecond = 0
interpolateMode mode = LIN
float unitDuration = 1
RBEPID myPID
RBEPID velocityPID
Protected Member Functions inherited from PIDMotor
double calcVel ()
float myFmap (float x, float in_min, float in_max, float out_min, float out_max)
float getSetPoint ()
Protected Attributes inherited from PIDMotor
long lastTimeRunPID = 0
double Setpoint = 0
double Input = 0
double Output = 0
bool lastErrPositive = false
double curTime = 0
double prevTime = 0
double timeInterval = 0
double movement = 0
double prevPos = 0
double Vel = 0
float startSetpoint = 0
float endSetpoint = 0
float startTime = 0
float duration = 0
Detailed Description
Definition at line 14 of file ServoAnalogPIDMotor.h.
Constructor & Destructor Documentation
ServoAnalogPIDMotor()
ServoAnalogPIDMotor::ServoAnalogPIDMotor ()
Definition at line 10 of file ServoAnalogPIDMotor.cpp.
References PIDMotor::setOutputBoundingValues().
Member Function Documentation
attach()
void ServoAnalogPIDMotor::attach (int servoPin, int analogPin)
Attach the hardware
Parameters
servoPin the pin number of the Servo PWM
analogPin the A channel of the encoder
Definition at line 17 of file ServoAnalogPIDMotor.cpp.
References adcPin, filterBuffer, filterIndex, filterSize, filterSum, getPosition(), motor, and PIDMotor::pidinit().
calcCur()
double ServoAnalogPIDMotor::calcCur (void) virtual
calcCur
Returns
calcCur
Implements PIDMotor.
Definition at line 54 of file ServoAnalogPIDMotor.cpp.
getPosition()
int64_t ServoAnalogPIDMotor::getPosition () virtual
getPosition
Returns
Position
Implements PIDMotor.
Definition at line 33 of file ServoAnalogPIDMotor.cpp.
References adcPin, filterBuffer, filterIndex, filterSize, filterSum, and offset.
Referenced by attach(), and overrideCurrentPositionHardware().
overrideCurrentPositionHardware()
void ServoAnalogPIDMotor::overrideCurrentPositionHardware (int64_t val) virtual
overrideCurrentPositionHardware
forces the hardware provider to return this value instead of its internal value and this position
Parameters
val the value to set the sensor to
Implements PIDMotor.
Definition at line 50 of file ServoAnalogPIDMotor.cpp.
References getPosition(), and offset.
setOutput()
void ServoAnalogPIDMotor::setOutput (int32_t out) virtual
virtual setOutput Set the motor in raw motor units
this value should be pre scalled to match the motors range the zero deadbanding should already be taken care of
Implements PIDMotor.
Definition at line 47 of file ServoAnalogPIDMotor.cpp.
References motor.
Field Documentation
adcPin
int ServoAnalogPIDMotor::adcPin =0 private
Definition at line 17 of file ServoAnalogPIDMotor.h.
Referenced by attach(), and getPosition().
filterBuffer
float ServoAnalogPIDMotor::filterBuffer[filterSize] private
Definition at line 19 of file ServoAnalogPIDMotor.h.
Referenced by attach(), and getPosition().
filterIndex
int ServoAnalogPIDMotor::filterIndex =0 private
Definition at line 20 of file ServoAnalogPIDMotor.h.
Referenced by attach(), and getPosition().
filterSum
float ServoAnalogPIDMotor::filterSum =0 private
Definition at line 21 of file ServoAnalogPIDMotor.h.
Referenced by attach(), and getPosition().
motor
Servo ServoAnalogPIDMotor::motor private
Definition at line 16 of file ServoAnalogPIDMotor.h.
Referenced by attach(), and setOutput().
offset
int64_t ServoAnalogPIDMotor::offset =0 private
Definition at line 18 of file ServoAnalogPIDMotor.h.
Referenced by getPosition(), and overrideCurrentPositionHardware().
The documentation for this class was generated from the following files:
src/pid/ServoAnalogPIDMotor.h
src/pid/ServoAnalogPIDMotor.cpp