RBE 2000 level template code: PIDMotor Class Reference
PIDMotor Class Reference abstract
#include <PIDMotor.h>
Public Member Functions
int32_t getHardwareOutput ()
PIDMotor ()
virtual ~PIDMotor ()
void loop ()
void velocityLoop ()
void overrideCurrentPosition (int32_t val)
void setSetpoint (int32_t val)
void startInterpolation (float newSetpoint, long msTimeDuration, interpolateMode mode)
bool isInterpolationDone ()
float getInterpolationUnitIncrement ()
void setSetpointDegrees (float val)
void startInterpolationDegrees (float newSetpoint, long msTimeDuration, interpolateMode mode)
void SetTunings (double Kp, double Ki, double Kd)
void SetTuningsVelocity (double Kp, double Kd)
void setVelocityDegreesPerSecond (float degreesPerSecond)
void pidinit ()
float getSetPointDegrees ()
double getVelocityDegreesPerSecond ()
double getAngleDegrees ()
void setOutputUnitVector (float out)
void stop ()
int32_t getOutputMin ()
int32_t getOutputMax ()
int32_t getOutputMinDeadbad ()
int32_t getOutputMaxDeadbad ()
int32_t getOutputStop ()
double getFreeSpinMaxDegreesPerSecond ()
double ticksToDeg ()
void setOutputBoundingValues (int32_t outputMin, int32_t outputMax, int32_t outputStop, int32_t outputMinDeadbad, int32_t outputMaxDeadbad, double ticksToDeg, double getFreeSpinMaxDegreesPerSecond, double speedAtPositiveCreepValue)
virtual double calcCur (void)=0
virtual int64_t getPosition ()=0
virtual void overrideCurrentPositionHardware (int64_t val)=0
Data Fields
int32_t hardwareOutput = 0
float targetDegreesPerSecond = 0
interpolateMode mode = LIN
float unitDuration = 1
RBEPID myPID
RBEPID velocityPID
Protected Member Functions
virtual void setOutput (int32_t out)=0
double calcVel ()
float myFmap (float x, float in_min, float in_max, float out_min, float out_max)
float getSetPoint ()
Protected Attributes
long lastTimeRunPID = 0
double Setpoint = 0
double Input = 0
double Output = 0
bool lastErrPositive = false
double curTime = 0
double prevTime = 0
double timeInterval = 0
double movement = 0
double prevPos = 0
double Vel = 0
float startSetpoint = 0
float endSetpoint = 0
float startTime = 0
float duration = 0
Private Attributes
int32_t outputMin = -100
int32_t outputMax = 100
int32_t outputMinDeadbad = 0
int32_t outputMaxDeadbad = 0
int32_t outputStop = 0
double myTicksToDeg =1
double freeSpinMaxDegreesPerSecond =1000
double freeSpinMinDegreesPerSecond =100
Detailed Description
Definition at line 19 of file PIDMotor.h.
Constructor & Destructor Documentation
PIDMotor()
PIDMotor::PIDMotor ()
Definition at line 25 of file PIDMotor.cpp.
References prevTime, and Vel.
~PIDMotor()
PIDMotor::~PIDMotor () virtual
Definition at line 30 of file PIDMotor.cpp.
Member Function Documentation
calcCur()
virtual double PIDMotor::calcCur (void) pure virtual
calcCur
Returns
calcCur
Implemented in HBridgeEncoderPIDMotor, ServoAnalogPIDMotor, and ServoEncoderPIDMotor.
calcVel()
double PIDMotor::calcVel () protected
Returns Vel in degress/second
Returns
Returns Vel in degress/second
Definition at line 225 of file PIDMotor.cpp.
References curTime, getPosition(), movement, prevPos, prevTime, ticksToDeg(), timeInterval, and Vel.
Referenced by getVelocityDegreesPerSecond(), and loop().
getAngleDegrees()
double PIDMotor::getAngleDegrees ()
Get the current position of the motor converted to Degrees
Returns
teh position in degrees
Definition at line 215 of file PIDMotor.cpp.
References getPosition(), and ticksToDeg().
Referenced by GetPIDData::event(), and StudentsRobot::updateStateMachine().
getFreeSpinMaxDegreesPerSecond()
double PIDMotor::getFreeSpinMaxDegreesPerSecond ()
getFreeSpinMaxDegreesPerSecond
Returns
FreeSpinMaxDegreesPerSecond
Definition at line 390 of file PIDMotor.cpp.
References freeSpinMaxDegreesPerSecond.
Referenced by setOutputBoundingValues(), setVelocityDegreesPerSecond(), and velocityLoop().
getHardwareOutput()
int32_t PIDMotor::getHardwareOutput ()
The value that is being sent to the hardware
View this variable in order to see what value is being sent to the motor directly
Definition at line 407 of file PIDMotor.cpp.
References hardwareOutput.
getInterpolationUnitIncrement()
float PIDMotor::getInterpolationUnitIncrement ()
getInterpolationUnitIncrement A unit vector from 0 to 1 representing the state of the interpolation.
Definition at line 40 of file PIDMotor.cpp.
References duration, mode, SIN, startTime, and unitDuration.
Referenced by isInterpolationDone(), and loop().
getOutputMax()
int32_t PIDMotor::getOutputMax ()
getOutputMax
Returns
OutputMax
Definition at line 355 of file PIDMotor.cpp.
References outputMax.
Referenced by setOutputUnitVector().
getOutputMaxDeadbad()
int32_t PIDMotor::getOutputMaxDeadbad ()
getOutputMaxDeadbad
Returns
OutputMaxDeadbad
Definition at line 373 of file PIDMotor.cpp.
References outputMaxDeadbad.
Referenced by HBridgeEncoderPIDMotor::setOutput(), and setOutputUnitVector().
getOutputMin()
int32_t PIDMotor::getOutputMin ()
getOutputMin
Returns
OutputMin
Definition at line 346 of file PIDMotor.cpp.
References outputMin.
Referenced by setOutputUnitVector().
getOutputMinDeadbad()
int32_t PIDMotor::getOutputMinDeadbad ()
getOutputMinDeadbad
Returns
OutputMinDeadbad
Definition at line 364 of file PIDMotor.cpp.
References outputMinDeadbad.
Referenced by setOutputUnitVector().
getOutputStop()
int32_t PIDMotor::getOutputStop ()
getOutputStop
Returns
OutputStop
Definition at line 382 of file PIDMotor.cpp.
References outputStop.
Referenced by setOutputUnitVector().
getPosition()
virtual int64_t PIDMotor::getPosition () pure virtual
getPosition
Returns
Position
Implemented in ServoAnalogPIDMotor, HBridgeEncoderPIDMotor, and ServoEncoderPIDMotor.
Referenced by calcVel(), getAngleDegrees(), loop(), SetTunings(), and stop().
getSetPoint()
float PIDMotor::getSetPoint () protected
Get the setpoint
Returns
the setpoint in sensor "Ticks"
Definition at line 188 of file PIDMotor.cpp.
References Setpoint.
Referenced by getSetPointDegrees().
getSetPointDegrees()
float PIDMotor::getSetPointDegrees ()
Get the setpoint
Returns
the setpoint in degrees
Definition at line 192 of file PIDMotor.cpp.
References getSetPoint(), and ticksToDeg().
Referenced by GetPIDData::event().
getVelocityDegreesPerSecond()
double PIDMotor::getVelocityDegreesPerSecond ()
Get the velocity of the plant
Returns
the velocity in DegreesPerSecond
Definition at line 210 of file PIDMotor.cpp.
References calcVel().
Referenced by GetPIDVelocity::event().
isInterpolationDone()
bool PIDMotor::isInterpolationDone ()
isInterpolationDone check if the interpolation is done or not
Returns
bool is the interpolation done
Definition at line 58 of file PIDMotor.cpp.
References getInterpolationUnitIncrement().
Referenced by StudentsRobot::updateStateMachine().
loop()
void PIDMotor::loop ()
Perform the PID calculations and apply the result to the actuators
Definition at line 64 of file PIDMotor.cpp.
References RBEPID::calc(), calcVel(), RBEPID::clearIntegralBuffer(), endSetpoint, getInterpolationUnitIncrement(), getPosition(), Input, lastErrPositive, lastTimeRunPID, mode, myPID, Output, RBEPID::sampleRateMs, setOutputUnitVector(), Setpoint, startSetpoint, unitDuration, VEL, and velocityLoop().
Referenced by StudentsRobot::pidLoop().
myFmap()
float PIDMotor::myFmap (float x, float in_min, float in_max, float out_min, float out_max) protected
myFmap local mapping function
Custom version of map with bound clamping built in.
Definition at line 16 of file PIDMotor.cpp.
Referenced by setOutputUnitVector(), and velocityLoop().
overrideCurrentPosition()
void PIDMotor::overrideCurrentPosition (int32_t val)
overrideCurrentPosition Set the current position to be the one provided
this is for calibrations
Definition at line 169 of file PIDMotor.cpp.
References RBEPID::clearIntegralBuffer(), LIN, myPID, overrideCurrentPositionHardware(), prevPos, and startInterpolation().
Referenced by SetTunings().
overrideCurrentPositionHardware()
virtual void PIDMotor::overrideCurrentPositionHardware (int64_t val) pure virtual
overrideCurrentPositionHardware
forces the hardware provider to return this value instead of its internal value and this position
Parameters
val the value to set the sensor to
Implemented in ServoAnalogPIDMotor, HBridgeEncoderPIDMotor, and ServoEncoderPIDMotor.
Referenced by overrideCurrentPosition().
pidinit()
void PIDMotor::pidinit ()
Reset and clear the PID controller
Definition at line 33 of file PIDMotor.cpp.
References RBEPID::clearIntegralBuffer(), and myPID.
Referenced by ServoEncoderPIDMotor::attach(), HBridgeEncoderPIDMotor::attach(), and ServoAnalogPIDMotor::attach().
setOutput()
virtual void PIDMotor::setOutput (int32_t out) protected pure virtual
virtual setOutput Set the motor in raw motor units
this value should be pre scalled to match the motors range the zero deadbanding should already be taken care of
Implemented in ServoAnalogPIDMotor, HBridgeEncoderPIDMotor, and ServoEncoderPIDMotor.
Referenced by setOutputUnitVector().
setOutputBoundingValues()
void PIDMotor::setOutputBoundingValues (int32_t outputMin, int32_t outputMax, int32_t outputStop, int32_t outputMinDeadbad, int32_t outputMaxDeadbad, double ticksToDeg, double getFreeSpinMaxDegreesPerSecond, double speedAtPositiveCreepValue)
Set the bounds of the output stage
These are the values to determing the opperating range of the output of this PID motor.
Parameters
outputMin the minimum value that the output takes (Full reverse)
outputMax the maximum value the output takes (Full forwared)
outputStop the value of the output to stop moving
outputMinDeadbad a positive value added to the stop value to creep backward
outputMaxDeadbad a positive value subtracted from stop value to creep forwards
ticksToDeg a value to convert from degrees to motor units. This number times degrees equals ticks;
freeSpinMaxDegreesPerSecond a value in degrees per second that represents the maximum freespinning speed of the motor running at 'outputMax'.
speedAtPositiveCreepValue the speed in degrees per second that the motor spins when the hardware output is at creep forwards
Definition at line 327 of file PIDMotor.cpp.
References freeSpinMaxDegreesPerSecond, freeSpinMinDegreesPerSecond, getFreeSpinMaxDegreesPerSecond(), myTicksToDeg, outputMax, outputMaxDeadbad, outputMin, outputMinDeadbad, outputStop, and ticksToDeg().
Referenced by HBridgeEncoderPIDMotor::HBridgeEncoderPIDMotor(), ServoAnalogPIDMotor::ServoAnalogPIDMotor(), ServoEncoderPIDMotor::ServoEncoderPIDMotor(), and StudentsRobot::StudentsRobot().
setOutputUnitVector()
void PIDMotor::setOutputUnitVector (float out)
setOutputUnitVector Set the output using a -1.0f to 1.0f unit vector.
Zero is stop This creates the dis-continuous signel needed to bypass deadbands in the actuator from a continous signel with range -1.0f to 1.0f.
Parameters
out the unit vector of the the motors output
Definition at line 137 of file PIDMotor.cpp.
References getOutputMax(), getOutputMaxDeadbad(), getOutputMin(), getOutputMinDeadbad(), getOutputStop(), hardwareOutput, myFmap(), Output, and setOutput().
Referenced by loop(), and velocityLoop().
setSetpoint()
void PIDMotor::setSetpoint (int32_t val)
setSetpoint Set the desired setpoint for the PID controller
the units for the variable is in sensor 'ticks' this will start a linear interpolation of 0 time
Definition at line 182 of file PIDMotor.cpp.
References LIN, and startInterpolation().
Referenced by setSetpointDegrees(), RobotControlCenter::setup(), and stop().
setSetpointDegrees()
void PIDMotor::setSetpointDegrees (float val)
setSetpointDegrees Set the desired setpoint for the PID controller
the units for the variable is in Degrees this will start a linear interpolation of 0 time
Definition at line 290 of file PIDMotor.cpp.
References setSetpoint(), and ticksToDeg().
SetTunings()
void PIDMotor::SetTunings (double Kp, double Ki, double Kd)
SetTunings Set the P.I.D. gains for the position controller
Parameters
Kp proportional gain
Ki integral gain
Kd derrivitive gain
Definition at line 202 of file PIDMotor.cpp.
References getPosition(), myPID, overrideCurrentPosition(), and RBEPID::setpid().
Referenced by SetPIDConstants::event().
SetTuningsVelocity()
void PIDMotor::SetTuningsVelocity (double Kp, double Kd)
SetTunings Set the P.I.D. gains for the velocity controller
Parameters
Kp proportional gain
Kd derrivitive gain
Note
KI must be 0 for velocity
Definition at line 115 of file PIDMotor.cpp.
References RBEPID::setpid(), and velocityPID.
setVelocityDegreesPerSecond()
void PIDMotor::setVelocityDegreesPerSecond (float degreesPerSecond)
Set the velocity of the motor
This function defaults to open-loop estimation of velocity
Parameters
degreesPerSecond the motor speed in degrees Per Second
Definition at line 119 of file PIDMotor.cpp.
References freeSpinMinDegreesPerSecond, getFreeSpinMaxDegreesPerSecond(), mode, stop(), targetDegreesPerSecond, and VEL.
Referenced by SetPIDVelocity::event().
startInterpolation()
void PIDMotor::startInterpolation (float newSetpoint, long msTimeDuration, interpolateMode mode)
Start a linear interpolation of the motor
The position setpoint will follow a trajectory over time the setpoint will start where it currently is, and arrive at the desired location after the number of msTimeDuration MS have elapsed. The trajectory can be either linear, with the LIN mode or the trajectory can be either Sinusoidal, with the SIN mode the units for the variable is in sensor 'ticks'
Parameters
newSetpoint the new setpoint in motor ticks
msTimeDuration the time of translation in miliseconds
mode The type of interpolation LIN or SIN
Note
To get immediate action set msTimeDuration to 0
Start a linear interpolation of the motor
The position setpoint will follow a trajectory over time the setpoint will start where it currently is, and arrive at the desired location after the number of msTimeDuration MS have elapsed. The trajectory can be either linear, with the LIN mode or the trajectory can be either Sinusoidal, with the SIN mode the units for the variable is in sensor 'ticks'
Parameters
newSetpoint the new setpoint
msTimeDuration the time of translation
mode The type of interpolation LIN or SIN
Definition at line 270 of file PIDMotor.cpp.
References duration, endSetpoint, mode, Setpoint, startSetpoint, and startTime.
Referenced by overrideCurrentPosition(), setSetpoint(), and startInterpolationDegrees().
startInterpolationDegrees()
void PIDMotor::startInterpolationDegrees (float newSetpoint, long msTimeDuration, interpolateMode mode)
Start a linear interpolation of the motor
The position setpoint will follow a trajectory over time the setpoint will start where it currently is, and arrive at the desired location after the number of msTimeDuration MS have elapsed. The trajectory can be either linear, with the LIN mode or the trajectory can be either Sinusoidal, with the SIN mode the units for the variable is in Degrees
Parameters
newSetpoint the new setpoint in degrees
msTimeDuration the time of translation in miliseconds
mode The type of interpolation LIN or SIN
Note
To get immediate action set msTimeDuration to 0
Start a linear interpolation of the motor
The position setpoint will follow a trajectory over time the setpoint will start where it currently is, and arrive at the desired location after the number of msTimeDuration MS have elapsed. The trajectory can be either linear, with the LIN mode or the trajectory can be either Sinusoidal, with the SIN mode the units for the variable is in Degrees
Parameters
newSetpoint the new setpoint in Degrees
msTimeDuration the time of translation
mode The type of interpolation LIN or SIN
Definition at line 307 of file PIDMotor.cpp.
References startInterpolation(), and ticksToDeg().
Referenced by SetPIDSetpoint::event(), and StudentsRobot::updateStateMachine().
stop()
void PIDMotor::stop ()
Stop the motion of the motor
Set the PID position to current position and use the position controller to hold pose
Definition at line 253 of file PIDMotor.cpp.
References getPosition(), and setSetpoint().
Referenced by setVelocityDegreesPerSecond(), and StudentsRobot::updateStateMachine().
ticksToDeg()
double PIDMotor::ticksToDeg ()
ticksToDeg
Returns
ticksToDeg
Definition at line 398 of file PIDMotor.cpp.
References myTicksToDeg.
Referenced by calcVel(), getAngleDegrees(), getSetPointDegrees(), setOutputBoundingValues(), setSetpointDegrees(), and startInterpolationDegrees().
velocityLoop()
void PIDMotor::velocityLoop ()
velocityLoop updates teh output in velocity mode
Definition at line 100 of file PIDMotor.cpp.
References freeSpinMinDegreesPerSecond, getFreeSpinMaxDegreesPerSecond(), myFmap(), setOutputUnitVector(), and targetDegreesPerSecond.
Referenced by loop().
Field Documentation
curTime
double PIDMotor::curTime = 0 protected
Definition at line 67 of file PIDMotor.h.
Referenced by calcVel().
duration
float PIDMotor::duration = 0 protected
Definition at line 91 of file PIDMotor.h.
Referenced by getInterpolationUnitIncrement(), and startInterpolation().
endSetpoint
float PIDMotor::endSetpoint = 0 protected
Definition at line 89 of file PIDMotor.h.
Referenced by loop(), and startInterpolation().
freeSpinMaxDegreesPerSecond
double PIDMotor::freeSpinMaxDegreesPerSecond =1000 private
Definition at line 54 of file PIDMotor.h.
Referenced by getFreeSpinMaxDegreesPerSecond(), and setOutputBoundingValues().
freeSpinMinDegreesPerSecond
double PIDMotor::freeSpinMinDegreesPerSecond =100 private
Definition at line 60 of file PIDMotor.h.
Referenced by setOutputBoundingValues(), setVelocityDegreesPerSecond(), and velocityLoop().
hardwareOutput
int32_t PIDMotor::hardwareOutput = 0
The value that is being sent to the hardware
View this variable in order to see what value is being sent to the motor directly
Definition at line 114 of file PIDMotor.h.
Referenced by GetPIDVelocity::event(), getHardwareOutput(), and setOutputUnitVector().
Input
double PIDMotor::Input = 0 protected
Definition at line 65 of file PIDMotor.h.
Referenced by loop().
lastErrPositive
bool PIDMotor::lastErrPositive = false protected
Definition at line 66 of file PIDMotor.h.
Referenced by loop().
lastTimeRunPID
long PIDMotor::lastTimeRunPID = 0 protected
Definition at line 63 of file PIDMotor.h.
Referenced by loop().
mode
interpolateMode PIDMotor::mode = LIN
Current interpolation mode
Definition at line 122 of file PIDMotor.h.
Referenced by GetPIDVelocity::event(), getInterpolationUnitIncrement(), loop(), setVelocityDegreesPerSecond(), and startInterpolation().
movement
double PIDMotor::movement = 0 protected
Definition at line 70 of file PIDMotor.h.
Referenced by calcVel().
myPID
RBEPID PIDMotor::myPID
The PID object for the position controller
Definition at line 137 of file PIDMotor.h.
Referenced by GetPIDConstants::event(), loop(), overrideCurrentPosition(), pidinit(), SetTunings(), and StudentsRobot::StudentsRobot().
myTicksToDeg
double PIDMotor::myTicksToDeg =1 private
Definition at line 49 of file PIDMotor.h.
Referenced by setOutputBoundingValues(), and ticksToDeg().
Output
double PIDMotor::Output = 0 protected
Definition at line 65 of file PIDMotor.h.
Referenced by loop(), and setOutputUnitVector().
outputMax
int32_t PIDMotor::outputMax = 100 private
getOutputMax
Returns
OutputMax
Definition at line 27 of file PIDMotor.h.
Referenced by getOutputMax(), and setOutputBoundingValues().
outputMaxDeadbad
int32_t PIDMotor::outputMaxDeadbad = 0 private
getOutputMaxDeadbad
Returns
OutputMaxDeadbad
Definition at line 39 of file PIDMotor.h.
Referenced by getOutputMaxDeadbad(), and setOutputBoundingValues().
outputMin
int32_t PIDMotor::outputMin = -100 private
Definition at line 21 of file PIDMotor.h.
Referenced by getOutputMin(), and setOutputBoundingValues().
outputMinDeadbad
int32_t PIDMotor::outputMinDeadbad = 0 private
getOutputMinDeadbad
Returns
OutputMinDeadbad
Definition at line 33 of file PIDMotor.h.
Referenced by getOutputMinDeadbad(), and setOutputBoundingValues().
outputStop
int32_t PIDMotor::outputStop = 0 private
getOutputStop
Returns
OutputStop
Definition at line 45 of file PIDMotor.h.
Referenced by getOutputStop(), and setOutputBoundingValues().
prevPos
double PIDMotor::prevPos = 0 protected
Definition at line 71 of file PIDMotor.h.
Referenced by calcVel(), and overrideCurrentPosition().
prevTime
double PIDMotor::prevTime = 0 protected
Definition at line 68 of file PIDMotor.h.
Referenced by calcVel(), and PIDMotor().
Setpoint
double PIDMotor::Setpoint = 0 protected
Definition at line 65 of file PIDMotor.h.
Referenced by getSetPoint(), loop(), and startInterpolation().
startSetpoint
float PIDMotor::startSetpoint = 0 protected
Definition at line 88 of file PIDMotor.h.
Referenced by loop(), and startInterpolation().
startTime
float PIDMotor::startTime = 0 protected
Definition at line 90 of file PIDMotor.h.
Referenced by getInterpolationUnitIncrement(), and startInterpolation().
targetDegreesPerSecond
float PIDMotor::targetDegreesPerSecond = 0
Target of the velocity degrees per second
Definition at line 118 of file PIDMotor.h.
Referenced by GetPIDVelocity::event(), setVelocityDegreesPerSecond(), and velocityLoop().
timeInterval
double PIDMotor::timeInterval = 0 protected
Definition at line 69 of file PIDMotor.h.
Referenced by calcVel().
unitDuration
float PIDMotor::unitDuration = 1
Duration of the interpolation mode, 1 equals done, 0 starting
Definition at line 133 of file PIDMotor.h.
Referenced by getInterpolationUnitIncrement(), and loop().
Vel
double PIDMotor::Vel = 0 protected
Definition at line 72 of file PIDMotor.h.
Referenced by calcVel(), and PIDMotor().
velocityPID
RBEPID PIDMotor::velocityPID
THe PID object for the velocity controller (UNIMPLEMENTED)
Definition at line 141 of file PIDMotor.h.
Referenced by GetPDVelocityConstants::event(), SetPDVelocityConstants::event(), SetTuningsVelocity(), and StudentsRobot::StudentsRobot().
The documentation for this class was generated from the following files:
src/pid/PIDMotor.h
src/pid/PIDMotor.cpp