RBE 2000 level template code: PickOrder Class Reference
PickOrder Class Reference
#include <PickOrder.h>
Public Member Functions
PickOrder (StudentsRobot *robot)
virtual ~PickOrder ()
void event (float *buffer)
Private Attributes
StudentsRobot * robotPointer
Detailed Description
Definition at line 7 of file PickOrder.h.
Constructor & Destructor Documentation
PickOrder()
PickOrder::PickOrder (StudentsRobot * robot) inline
Definition at line 11 of file PickOrder.h.
~PickOrder()
virtual PickOrder::~PickOrder () inline virtual
Definition at line 16 of file PickOrder.h.
References event().
Member Function Documentation
event()
void PickOrder::event (float * buffer)
Definition at line 6 of file PickOrder.cpp.
References StudentsRobot::PickOrder(), and robotPointer.
Referenced by ~PickOrder().
Field Documentation
robotPointer
StudentsRobot* PickOrder::robotPointer private
Definition at line 8 of file PickOrder.h.
Referenced by event().
The documentation for this class was generated from the following files:
src/commands/PickOrder.h
src/commands/PickOrder.cpp