RBE 2000 level template code: RBEPID Class Reference
RBEPID Class Reference
#include <RBEPID.h>
Public Member Functions
RBEPID ()
void setpid (float P, float I, float D)
float calc (double setPoint, double curPosition)
void clearIntegralBuffer ()
Data Fields
float kp = 0.00015
float ki = 0
float kd = 0
float last_error = 0
float sum_error = 0
int sampleRateMs = 5
Detailed Description
Definition at line 11 of file RBEPID.h.
Constructor & Destructor Documentation
RBEPID()
RBEPID::RBEPID ()
Definition at line 11 of file RBEPID.cpp.
Member Function Documentation
calc()
float RBEPID::calc (double setPoint, double curPosition)
calc the PID control signel
Parameters
setPoint is the setpoint of the PID system
curPosition the current position of the plan
Returns
a value from -1.0 to 1.0 representing the PID control signel
Definition at line 29 of file RBEPID.cpp.
References kp.
Referenced by PIDMotor::loop().
clearIntegralBuffer()
void RBEPID::clearIntegralBuffer ()
Clear the internal representation fo the integral term.
Definition at line 53 of file RBEPID.cpp.
Referenced by PIDMotor::loop(), PIDMotor::overrideCurrentPosition(), and PIDMotor::pidinit().
setpid()
void RBEPID::setpid (float P, float I, float D)
setpid set PID constants
Definition at line 16 of file RBEPID.cpp.
References kd, ki, and kp.
Referenced by SetPDVelocityConstants::event(), PIDMotor::SetTunings(), PIDMotor::SetTuningsVelocity(), and StudentsRobot::StudentsRobot().
Field Documentation
kd
float RBEPID::kd = 0
Definition at line 17 of file RBEPID.h.
Referenced by GetPIDConstants::event(), GetPDVelocityConstants::event(), and setpid().
ki
float RBEPID::ki = 0
Definition at line 16 of file RBEPID.h.
Referenced by GetPIDConstants::event(), GetPDVelocityConstants::event(), and setpid().
kp
float RBEPID::kp = 0.00015
Definition at line 15 of file RBEPID.h.
Referenced by calc(), GetPIDConstants::event(), GetPDVelocityConstants::event(), and setpid().
last_error
float RBEPID::last_error = 0
Definition at line 18 of file RBEPID.h.
sampleRateMs
int RBEPID::sampleRateMs = 5
Definition at line 20 of file RBEPID.h.
Referenced by PIDMotor::loop(), and StudentsRobot::StudentsRobot().
sum_error
float RBEPID::sum_error = 0
Definition at line 19 of file RBEPID.h.
The documentation for this class was generated from the following files:
RBEPID.h
RBEPID.cpp