RBE 2000 level template code: Approve Class Reference
Approve Class Reference
#include <Approve.h>
Public Member Functions
Approve (StudentsRobot *robot)
virtual ~Approve ()
void event (float *buffer)
Private Attributes
StudentsRobot * robotPointer
Detailed Description
Definition at line 6 of file Approve.h.
Constructor & Destructor Documentation
Approve()
Approve::Approve (StudentsRobot * robot) inline
Definition at line 10 of file Approve.h.
~Approve()
virtual Approve::~Approve () inline virtual
Definition at line 15 of file Approve.h.
References event().
Member Function Documentation
event()
void Approve::event (float * buffer)
Definition at line 6 of file Approve.cpp.
References StudentsRobot::Approve(), and robotPointer.
Referenced by ~Approve().
Field Documentation
robotPointer
StudentsRobot* Approve::robotPointer private
Definition at line 7 of file Approve.h.
Referenced by event().
The documentation for this class was generated from the following files:
src/commands/Approve.h
src/commands/Approve.cpp