RBE 2000 level template code: EStop Class Reference
EStop Class Reference
#include <EStop.h>
Public Member Functions
EStop (StudentsRobot *robot)
~EStop ()
void event (float *buffer)
Private Attributes
StudentsRobot * robotPointer
Detailed Description
Definition at line 13 of file EStop.h.
Constructor & Destructor Documentation
EStop::EStop (StudentsRobot * robot) inline
Definition at line 16 of file EStop.h.
EStop::~EStop () inline
Definition at line 21 of file EStop.h.
References event().
Member Function Documentation
void EStop::event (float * buffer)
Definition at line 10 of file EStop.cpp.
References StudentsRobot::EStop(), and robotPointer.
Referenced by ~EStop().
Field Documentation
StudentsRobot* EStop::robotPointer private
Definition at line 14 of file EStop.h.
Referenced by event().
The documentation for this class was generated from the following files:
src/commands/EStop.h
src/commands/EStop.cpp