RBE 2000 level template code: ServoEncoderPIDMotor Class Reference
ServoEncoderPIDMotor Class Reference
#include <ServoEncoderPIDMotor.h>
Public Member Functions
ServoEncoderPIDMotor ()
virtual ~ServoEncoderPIDMotor ()
void attach (int servoPin, int encoderA, int encoderB)
int64_t getPosition ()
void setOutput (int64_t out)
void overrideCurrentPositionHardware (int64_t val)
double calcCur (void)
Public Member Functions inherited from PIDMotor
PIDMotor ()
virtual ~PIDMotor ()
void loop ()
void velocityLoop ()
void overrideCurrentPosition (int64_t val)
void setSetpoint (int64_t val)
void startInterpolation (float newSetpoint, long msTimeDuration, interpolateMode mode)
bool isInterpolationDone ()
float getInterpolationUnitIncrement ()
void setSetpointDegrees (float val)
void startInterpolationDegrees (float newSetpoint, long msTimeDuration, interpolateMode mode)
void SetTunings (double Kp, double Ki, double Kd)
void SetTuningsVelocity (double Kp, double Kd)
void setVelocityDegreesPerSecond (float degreesPerSecond)
void pidinit ()
float getSetPointDegrees ()
double getVelocityDegreesPerSecond ()
double getAngleDegrees ()
void setOutputUnitVector (float out)
void stop ()
int64_t getOutputMin ()
int64_t getOutputMax ()
int64_t getOutputMinDeadbad ()
int64_t getOutputMaxDeadbad ()
int64_t getOutputStop ()
double getFreeSpinMaxDegreesPerSecond ()
double ticksToDeg ()
void setOutputBoundingValues (int64_t outputMin, int64_t outputMax, int64_t outputStop, int64_t outputMinDeadbad, int64_t outputMaxDeadbad, double ticksToDeg, double getFreeSpinMaxDegreesPerSecond)
Data Fields
ESP32Encoder encoder
Servo motor
Data Fields inherited from PIDMotor
float unitDuration = 1
RBEPID myPID
RBEPID velocityPID
int64_t hardwareOutput = 0
Additional Inherited Members
Protected Member Functions inherited from PIDMotor
double calcVel ()
float myFmap (float x, float in_min, float in_max, float out_min, float out_max)
float getSetPoint ()
Protected Attributes inherited from PIDMotor
long lastTimeRunPID = 0
double Setpoint = 0
double Input = 0
double Output = 0
bool lastErrPositive = false
double curTime = 0
double prevTime = 0
double timeInterval = 0
double movement = 0
double prevPos = 0
double Vel = 0
float startSetpoint = 0
float endSetpoint = 0
float startTime = 0
float duration = 0
interpolateMode mode = LIN
float targetDegreesPerSecond = 0
Detailed Description
Definition at line 14 of file ServoEncoderPIDMotor.h.
Constructor & Destructor Documentation
ServoEncoderPIDMotor::ServoEncoderPIDMotor ()
Definition at line 10 of file ServoEncoderPIDMotor.cpp.
References encoder, and PIDMotor::setOutputBoundingValues().
ServoEncoderPIDMotor::~ServoEncoderPIDMotor () virtual
Definition at line 20 of file ServoEncoderPIDMotor.cpp.
Member Function Documentation
void ServoEncoderPIDMotor::attach (int servoPin, int encoderA, int encoderB)
Attach the hardware
Parameters
servoPin the pin number of the Servo PWM
encoderA the A channel of the encoder
encoderB the B channel of the encoder
Definition at line 24 of file ServoEncoderPIDMotor.cpp.
References encoder, motor, and PIDMotor::pidinit().
Referenced by StudentsRobot::StudentsRobot().
double ServoEncoderPIDMotor::calcCur (void) virtual
calcCur
Returns
calcCur
Implements PIDMotor.
Definition at line 37 of file ServoEncoderPIDMotor.cpp.
int64_t ServoEncoderPIDMotor::getPosition () virtual
getPosition
Returns
Position
Implements PIDMotor.
Definition at line 40 of file ServoEncoderPIDMotor.cpp.
References encoder.
Referenced by StudentsRobot::StudentsRobot().
void ServoEncoderPIDMotor::overrideCurrentPositionHardware (int64_t val) virtual
overrideCurrentPositionHardware
forces the hardware provider to return this value instead of its internal value and this position
Parameters
val the value to set the sensor to
Implements PIDMotor.
Definition at line 34 of file ServoEncoderPIDMotor.cpp.
References encoder.
void ServoEncoderPIDMotor::setOutput (int64_t out) virtual
virtual setOutput Set the motor in raw motor units
this value should be pre scalled to match the motors range the zero deadbanding should already be taken care of
Implements PIDMotor.
Definition at line 31 of file ServoEncoderPIDMotor.cpp.
References motor.
Field Documentation
ESP32Encoder ServoEncoderPIDMotor::encoder
Definition at line 32 of file ServoEncoderPIDMotor.h.
Referenced by attach(), getPosition(), overrideCurrentPositionHardware(), ServoEncoderPIDMotor(), and StudentsRobot::StudentsRobot().
Servo ServoEncoderPIDMotor::motor
Definition at line 33 of file ServoEncoderPIDMotor.h.
Referenced by attach(), and setOutput().
The documentation for this class was generated from the following files:
src/pid/ServoEncoderPIDMotor.h
src/pid/ServoEncoderPIDMotor.cpp