RBE 2000 level template code: StudentsRobot Class Reference
StudentsRobot Class Reference
#include <StudentsRobot.h>
Public Member Functions
StudentsRobot (PIDMotor *motor1, PIDMotor *motor2, PIDMotor *motor3, Servo *servo)
void Approve (float *buffer)
void ClearFaults (float *buffer)
void EStop (float *buffer)
void PickOrder (float *buffer)
void pidLoop ()
void updateStateMachine ()
Data Fields
ComStackStatusState myCommandsStatus = Ready_for_new_task
RobotStateMachine status = StartupRobot
Private Attributes
PIDMotor * motor1
PIDMotor * motor2
PIDMotor * motor3
Servo * servo
float lsensorVal =0
float rsensorVal =0
long nextTime =0
long startTime =0
RobotStateMachine nextStatus = StartupRobot
Detailed Description
Definition at line 52 of file StudentsRobot.h.
Constructor & Destructor Documentation
StudentsRobot()
StudentsRobot::StudentsRobot (PIDMotor * motor1, PIDMotor * motor2, PIDMotor * motor3, Servo * servo)
Constructor for StudentsRobot
attach the 4 actuators
these are the 4 actuators you need to use for this lab all 4 must be attached at this time DO NOT reuse pins or fail to attach any of the objects
Definition at line 10 of file StudentsRobot.cpp.
References ANALOG_SENSE_ONE, ANALOG_SENSE_TWO, H_BRIDGE_ENABLE, motor1, motor2, motor3, PIDMotor::myPID, RBEPID::sampleRateMs, servo, PIDMotor::setOutputBoundingValues(), RBEPID::setpid(), and PIDMotor::velocityPID.
Member Function Documentation
Approve()
void StudentsRobot::Approve (float * buffer)
Approve
Parameters
buffer A buffer of floats containing nothing
the is the event of the Approve button pressed in the GUI
This function is called via coms.server() in:
See also
RobotControlCenter::fastLoop
Definition at line 167 of file StudentsRobot.cpp.
References myCommandsStatus, Ready_for_new_task, Waiting_for_approval_to_dropoff, and Waiting_for_approval_to_pickup.
Referenced by Approve::event().
ClearFaults()
void StudentsRobot::ClearFaults (float * buffer)
ClearFaults
Parameters
buffer A buffer of floats containing nothing
this represents the event of the clear faults button press in the gui
This function is called via coms.server() in:
See also
RobotControlCenter::fastLoop
Definition at line 187 of file StudentsRobot.cpp.
References myCommandsStatus, Ready_for_new_task, StartRunning, and status.
Referenced by ClearFaults::event().
EStop()
void StudentsRobot::EStop (float * buffer)
EStop
Parameters
buffer A buffer of floats containing nothing
this represents the event of the EStop button press in the gui
This is called whrn the estop in the GUI is pressed All motors shuld hault and lock in position Motors should not go idle and drop the plate
This function is called via coms.server() in:
See also
RobotControlCenter::fastLoop
Definition at line 208 of file StudentsRobot.cpp.
References Fault_E_Stop_pressed, Halting, myCommandsStatus, and status.
Referenced by EStop::event().
PickOrder()
void StudentsRobot::PickOrder (float * buffer)
PickOrder
Parameters
buffer A buffer of floats containing the pick order data
buffer[0] is the material, aluminum or plastic.
buffer[1] is the drop off angle 25 or 45 degrees
buffer[2] is the drop off position 1, or 2
This function is called via coms.server() in:
See also
RobotControlCenter::fastLoop
Definition at line 227 of file StudentsRobot.cpp.
References myCommandsStatus, and Waiting_for_approval_to_pickup.
Referenced by PickOrder::event().
pidLoop()
void StudentsRobot::pidLoop ()
pidLoop This functoion is called to let the StudentsRobot controll the running of the PID loop functions
The loop function on all motors needs to be run when this function is called and return fast
This is run fast and should return fast
You call the PIDMotor's loop function. This will update the whole motor control system This will read from the concoder and write to the motors and handle the hardware interface. Instead of allowing this to be called by the controller yopu may call these from a timer interrupt.
Definition at line 152 of file StudentsRobot.cpp.
References PIDMotor::loop(), motor1, motor2, and motor3.
Referenced by RobotControlCenter::fastLoop().
updateStateMachine()
void StudentsRobot::updateStateMachine ()
updateStateMachine use the stub state machine as a starting point.
the students state machine can be updated with this function
Seperate from running the motor control, update the state machine for running the final project code here
Definition at line 82 of file StudentsRobot.cpp.
References PIDMotor::getAngleDegrees(), H_BRIDGE_ENABLE, Halt, Halting, PIDMotor::isInterpolationDone(), motor1, motor2, motor3, nextStatus, nextTime, Running, SIN, PIDMotor::startInterpolationDegrees(), StartRunning, startTime, StartupRobot, status, PIDMotor::stop(), WAIT_FOR_MOTORS_TO_FINNISH, and WAIT_FOR_TIME.
Referenced by RobotControlCenter::fastLoop().
Field Documentation
lsensorVal
float StudentsRobot::lsensorVal =0 private
Definition at line 58 of file StudentsRobot.h.
motor1
PIDMotor* StudentsRobot::motor1 private
Definition at line 54 of file StudentsRobot.h.
Referenced by pidLoop(), StudentsRobot(), and updateStateMachine().
motor2
PIDMotor* StudentsRobot::motor2 private
Definition at line 55 of file StudentsRobot.h.
Referenced by pidLoop(), StudentsRobot(), and updateStateMachine().
motor3
PIDMotor* StudentsRobot::motor3 private
Definition at line 56 of file StudentsRobot.h.
Referenced by pidLoop(), StudentsRobot(), and updateStateMachine().
myCommandsStatus
ComStackStatusState StudentsRobot::myCommandsStatus = Ready_for_new_task
Command status
this is sent upstream to the Java GUI to notify it of current state
Definition at line 82 of file StudentsRobot.h.
Referenced by Approve(), ClearFaults(), EStop(), GetStatus::event(), and PickOrder().
nextStatus
RobotStateMachine StudentsRobot::nextStatus = StartupRobot private
Definition at line 62 of file StudentsRobot.h.
Referenced by updateStateMachine().
nextTime
long StudentsRobot::nextTime =0 private
Definition at line 60 of file StudentsRobot.h.
Referenced by updateStateMachine().
rsensorVal
float StudentsRobot::rsensorVal =0 private
Definition at line 59 of file StudentsRobot.h.
servo
Servo* StudentsRobot::servo private
Definition at line 57 of file StudentsRobot.h.
Referenced by StudentsRobot().
startTime
long StudentsRobot::startTime =0 private
Definition at line 61 of file StudentsRobot.h.
Referenced by updateStateMachine().
status
RobotStateMachine StudentsRobot::status = StartupRobot
This is internal data representing the runtime status of the robot for use in its state machine
Definition at line 86 of file StudentsRobot.h.
Referenced by ClearFaults(), EStop(), and updateStateMachine().
The documentation for this class was generated from the following files:
StudentsRobot.h
StudentsRobot.cpp